formatter: "markdown"

recursive:
  enabled: false
  path: modules

output:
  file: "README.md"
  mode: replace

settings:
  color: false
  description: "true"
  hide-empty: true
  read-comments: true
  sensitive: true
  lockfile: true

sort:
  enabled: true
  by: required

content: |-
  {{ .Header }}

  {{ include "Installation.md" }}

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}  